name: AsyncAPI documents processing

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Generating HTML from my AsyncAPI document
        run: "npx --yes -p @asyncapi/generator ag ./asyncapi.yml @asyncapi/html-template -o ./generated-html --force-write"
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'generated-html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1